### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by doozMen** [icapps/ios-faro#17]
There are no test yet and they perform a real network call. This code needs some love and unit tests that don't require unit testing

**Comment by herre** [comment]
Xcode code coverage currently seems not to be working (only test covering the Example app are taken into account)

cfr https://github.com/CocoaPods/CocoaPods/issues/3706

**Comment by doozMen** [comment]
I made an issue #23 for enable code coverage. For now we can leave this but good find! @herre
