### ISSUE TITLE
Naming needs some <3

### ISSUE THREAD

**Issue by doozMen** [icapps/ios-faro#18]
Look at [Marc Zara talk on Realm](https://realm.io/news/slug-marcus-zarra-exploring-mvcn-swift/). 

Let it inspire you to rename and restructure the project.

**Comment by herre** [comment]
gebruiken we "AR" als prefix?

**Comment by doozMen** [comment]
Ik ben niet van een Prefix. Alle classes binnen een swift framework worden al met AirRivet.class geprefixt  omdat ze in een framework zitten. Maar dat is mijn mening.

Welk probleem zou je willen oplossen met de AR prefix?

**Comment by fousa** [comment]
I'll give it a try.

Sorry @doozMen but I'll have to refactor `migitable` before my brain explodes.

![](http://gif.co/wisJ.gif)

**Comment by doozMen** [comment]
@fousa Ok I can understand that. I also have a idea but no time yet to explain. Friday with beer?
