### ISSUE TITLE
Choose a Mapper

### ISSUE THREAD

**Issue by doozMen** [icapps/ios-faro#19]
Now there are some issues with when using pod Argo with the required init. See how to deal with this.
- [ ]  required init problem
- [ ] which mapper do we want to use
- [ ] is pod spec correct to include the dependency.

**Comment by HannesVDB** [comment]
Some other mappers we could take a look at
- ObjectMapper: https://github.com/Hearst-DD/ObjectMapper
- SwiftyJSON: https://github.com/SwiftyJSON/SwiftyJSON
- JSONJoy-Swift: https://github.com/daltoniam/JSONJoy-Swift
- Argo: https://cocoapods.org/?q=Argo -> Is al gekend bij @herre

**Comment by HannesVDB** [comment]
Another interesting read is this: https://www.bignerdranch.com/blog/introducing-freddy-an-open-source-framework-for-parsing-json-in-swift/

https://github.com/bignerdranch/Freddy

**Comment by doozMen** [comment]
Ok ik neem dit vandaag op want ook nodig voor een intern project. Bedankt alvast voor het opzoekingswerk!
